{
    "testdef_repos": [

        {
            "git-repo": "https://github.com/wangyingtaodeepin/lava-autologin.git",
            "testdef": "dde-launch-end.yaml",
            "parameters": {
                "AUTO_LOGIN_USER": "deepin"
            },
            "minimal_tags": ["wifi-ar9485"]
        }
    ],
    "stream": "/anonymous/test/",
    "timeout": 18000,
    "name": "run-testlink-plan"
}
